const db = require('./connection');
const { User, Pledge, Home, Travel } = require('../models');

db.once('open', async () => {
  await Pledge.deleteMany();

  const pledge = await Pledge.insertMany([
    {
      action: 'Purchase Electric Vehicle',
      description: '',
      icon: 'bxs:car',
      link: 'https://www.epa.gov/greenvehicles/explaining-electric-plug-hybrid-electric-vehicles',
    },
    {
      action: 'Purchase Hybrid Vehicle',
      description: '',
      icon: 'bxs:car',
      link: 'https://www.epa.gov/greenvehicles/explaining-electric-plug-hybrid-electric-vehicles',
    },
    {
      action: 'Install Solar Panels',
      description: '',
      icon: 'material-symbols:solar-power-outline-rounded',
      link: 'https://www.epa.gov/sustainable-water-infrastructure/solar-cells-renewable-energy-fact-sheet',
    },
    {
      action: 'Purchase Green Electricity',
      description: '',
      icon: 'healthicons:electricity-outline',
      link: 'https://www.epa.gov/greenpower',
    },
    {
      action: 'Use Public Transportation',
      description: '',
      icon: 'zondicons:travel-train',
      link: 'https://www.epa.gov/smartgrowth/smart-growth-and-transportation',
    },
    {
      action: 'Walk or Bike',
      description: '',
      icon: 'ic:round-directions-bike',
      link: 'https://www.epa.gov/greenvehicles/what-if-we-kept-our-cars-parked-trips-less-one-mile',
    },
    {
      action: 'Install Tankless Water Heater',
      description: '',
      icon: 'material-symbols:water-heater-outline',
      link: 'https://www.energy.gov/energysaver/tankless-or-demand-type-water-heaters',
    },
    {
      action: 'Use Energy Star Appliances',
      description: '',
      icon: 'cil:fridge',
      link: 'https://www.energystar.gov/products',
    },
    {
      action: 'Reduce Air Travel',
      description: '',
      icon: 'fa6-solid:plane',
      link: 'https://www.epa.gov/regulations-emissions-vehicles-and-engines/regulations-greenhouse-gas-emissions-aircraft',
    },
    {
      action: 'Eat a Low Carbon Diet',
      description: '',
      icon: 'fluent:food-24-filled',
      link: 'https://shrinkthatfootprint.com/food-carbon-footprint-diet/',
    },
    {
      action: 'Regulate Thermostat',
      description: '',
      icon: 'material-symbols:mode-heat-cool',
      link: 'https://www.energy.gov/energysaver/programmable-thermostats',
    },
    {
      action: 'Install Low Flow Showerhead',
      description: '',
      icon: 'bx:water',
      link: 'https://www.epa.gov/watersense/showerheads',
    },
    {
      action: 'Use LED Lightbulbs',
      description: '',
      icon: 'healthicons:electricity-outline',
      link: 'https://www.energy.gov/energysaver/lighting-choices-save-you-money',
    },
    {
      action: 'Use Rechargable Batteries',
      description: '',
      icon: 'akar-icons:battery-charging',
      link: 'https://blueandgreentomorrow.com/environment/rechargeable-batteries-savior-in-fight-against-climate-change/',
    },
    {
      action: 'Install Water Efficient Landscaping',
      description: '',
      icon: 'bx:water',
      link: 'https://www.energy.gov/energysaver/landscaping-water-conservation',
    },
  ]);

  console.log('Pledges seeded');

  // Do we want all of this to be seeded with the user? I'll put it there for now
  // await Home.deleteMany();

  // const home = await Home.insertMany([]);

  // console.log('Home data seeded');

  // await Travel.deleteMany();

  // const travel = await Travel.insertMany([]);

  console.log('Travel data seeded');

  await User.deleteMany();

  await User.create([
    { 
      name: 'Greta Thunberg',
      email: 'gretasavestheworld@gmail.com',
      password: 'password12345',
      car: 'small',
      vehicleMilesPerYear: 20000,
      train: 'no',
      trainMiles: 0,
      bus: 'no',
      busMiles: 0,
      plane: 'yes',
      airTravel: 70000,
      showers: 182,
      showerMinutes: 15,
      flushes: 1095,
      bottles: 1825,
      laundry: 52,
      fridge: 'yes',
      TV: 'yes',
      TVHours: 730,
      desktop: 'no',
      desktopHours:0,
      laptop: 'yes',
      laptopHours: 365,
      monitor: 'no',
      monitorHours: 0,
      climate: 'cold',
      size: 1500,
      air: 'no',
      airDays: 0,
      gas: 'yes',
      gasDays: 180,
      oil: 'no',
      oilDays: 0
     },
     { 
      name: 'John Muir',
      email: 'johninthewild@yahoo.com',
      password: 'password54321',
      car: 'average',
      vehicleMilesPerYear: 40000,
      train: 'yes',
      trainMiles: 10000,
      bus: 'no',
      busMiles: 0,
      plane: 'no',
      airTravel: 0,
      showers: 100,
      showerMinutes: 30,
      flushes: 1000,
      bottles: 1900,
      laundry: 40,
      fridge: 'yes',
      TV: 'no',
      TVHours: 0,
      desktop: 'yes',
      desktopHours: 1460,
      laptop: 'no',
      laptopHours: 0,
      monitor: 'no',
      monitorHours: 0,
      climate: 'cool',
      size: 800,
      air: 'yes',
      airDays: 60,
      gas: 'no',
      gasDays: 0,
      oil: 'yes',
      oilDays: 90
     },
     { 
      name: 'Wangari Maathai',
      email: 'wmaathai@earthsave.com',
      password: 'password23456',
      car: 'hybrid',
      vehicleMilesPerYear: 24000,
      train: 'no',
      trainMiles: 0,
      bus: 'yes',
      busMiles: 15000,
      plane: 'yes',
      airTravel: 10000,
      showers: 365,
      showerMinutes: 10,
      flushes: 730,
      bottles: 2500,
      laundry: 60,
      fridge: 'yes',
      TV: 'yes',
      TVHours: 365,
      desktop: 'yes',
      desktopHours: 1000,
      laptop: 'no',
      laptopHours: 0,
      monitor: 'yes',
      monitorHours: 1000,
      climate: 'hot',
      size: 2000,
      air: 'yes',
      airDays: 200,
      gas: 'no',
      gasDays: 0,
      oil: 'no',
      oilDays: 0
     },
     { 
      name: 'David Brower',
      email: 'dbrowersierra@hotmail.com',
      password: 'password65432',
      car: 'SUV',
      vehicleMilesPerYear: 30000,
      train: 'no',
      trainMiles: 0,
      bus: 'yes',
      busMiles: 8000,
      plane: 'no',
      airTravel: 0,
      showers: 150,
      showerMinutes: 40,
      flushes: 365,
      bottles: 1100,
      laundry: 26,
      fridge: 'no',
      TV: 'no',
      TVHours: 0,
      desktop: 'no',
      desktopHours: 0,
      laptop: 'yes',
      laptopHours: 1825,
      monitor: 'yes',
      monitorHours: 1825,
      climate: 'moderate',
      size: 2500,
      air: 'yes',
      airDays: 90,
      gas: 'no',
      gasDays: 0,
      oil: 'yes',
      oilDays: 60
     },
     { 
      name: 'Winona LaDuke',
      email: 'winonald@example.com',
      password: 'password56789',
      car: 'none',
      vehicleMilesPerYear: 0,
      train: 'yes',
      trainMiles: 50000,
      bus: 'no',
      busMiles: 0,
      plane: 'yes',
      airTravel: 12000,
      showers: 365,
      showerMinutes: 15,
      flushes: 2190,
      bottles: 3000,
      laundry: 52,
      fridge: 'yes',
      TV: 'yes',
      TVHours: 730,
      desktop: 'no',
      desktopHours: 0,
      laptop: 'no',
      laptopHours: 0,
      monitor: 'no',
      monitorHours: 0,
      climate: 'warm',
      size: 3000,
      air: 'yes',
      airDays: 182,
      gas: 'yes',
      gasDays: 183,
      oil: 'no',
      oilDays: 0
     },
     { 
      name: 'Chico Mendez',
      email: 'rainforestsforever@aol.com',
      password: 'password98765',
      car: 'average',
      vehicleMilesPerYear: 48000,
      train: 'no',
      trainMiles: 0,
      bus: 'no',
      busMiles: 0,
      plane: 'no',
      airTravel: 0,
      showers: 365,
      showerMinutes: 45,
      flushes: 730,
      bottles: 1000,
      laundry: 104,
      fridge: 'yes',
      TV: 'yes',
      TVHours: 1095,
      desktop: 'yes',
      desktopHours: 365,
      laptop: 'no',
      laptopHours: 0,
      monitor: 'no',
      monitorHours: 0,
      climate: 'hot',
      size: 2100,
      air: 'yes',
      airDays: 300,
      gas: 'no',
      gasDays: 0,
      oil: 'no',
      oilDays: 0
     }
  ]);

  console.log('Users seeded');

  process.exit();
});
